name: Python CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install RobotPy
        run: |
          python -m pip install --upgrade pip
          pip install robotpy[all]

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotpy[all] flake8

      - name: Run Syntax Check (Lint)
        run: |
          # Use flake8 to check for syntax errors and undefined names
          # --select=E9,F63,F7,F82 allows the build to fail on logic errors but ignore formatting
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics